# This is a basic workflow to help you get started with Actions

name: User API CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: [ 'user-api/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'user-api/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
      name: Check out repository
    - uses: actions/setup-node@v1
      name: Set up Node.js
      with:
        node-version: 14
    - run: |
        npm ci
      name: Build
      working-directory: ./user-api
